{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AWSConfigBucketPermissionsCheck",
            "Effect": "Allow",
            "Principal": {
                "Service": "config.amazonaws.com"
            },
            "Action": "s3:GetBucketAcl",
            "Resource": "arn:aws:s3:::security-logs-711387102447",
            "Condition": {
                "StringEquals": {
                    "AWS:SourceAccount": "711387102447"
                }
            }
        },
        {
            "Sid": "AWSConfigBucketExistenceCheck",
            "Effect": "Allow",
            "Principal": {
                "Service": "config.amazonaws.com"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::security-logs-711387102447",
            "Condition": {
                "StringEquals": {
                    "AWS:SourceAccount": "711387102447"
                }
            }
        },
        {
            "Sid": "AWSConfigBucketDelivery",
            "Effect": "Allow",
            "Principal": {
                "Service": "config.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::security-logs-711387102447/AWSLogs/711387102447/Config/*",
            "Condition": {
                "StringEquals": {
                    "AWS:SourceAccount": "711387102447",
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        }
    ]
}